### ISSUE TITLE
bad results for sus-sd

### ISSUE THREAD

**Issue by Adasunnylily** [vishaal27/SuS-X#4] opened 2023-09-03 04:15 UTC
hi, great work!
I met a problem when I tried to reproduce your results for cub in table12, the results I got for SuS-X-SD-C is barely the same with  zero-shot clip about 41 not 48 as reported in the paper. The code I use for generate cub support dataset  is 
` python generate_sd_sus.py --dataset cub --num_images 15 --prompt_shorthand cupl  --huggingface_key xxxx'
the code I used for feature extraction is 
` python encode_sus_sd.py --dataset cub --prompt_shorthand cupl`
the code I used for inference is 
 python tipx.py --dataset cub --backbone RN50 --prompt_shorthand cupl --sus_type sd
Could you please tell me the possible reason why I got this results and how can  I fix these?
What's more, I  found some generated  samples look far from the original dataset, is these a common problem resulting from the diffusion or did I  do something wrong? 
Could you please release the dataset you generated for the report results？
Thanks a lot！

**Comment by vishaal27** [comment] 2023-09-03 07:42
Hi, thanks for the question.

It seems like you are using the number of support set images as 15. Our optimal results were obtained with two support-set samples per class (so 400 in total). You can see the optimal number of support set examples in table 8 of the appendix. Further, to ensure that there aren't any disparities due to the environment and random seeds, I'd recommend checking that you are able to reproduce the SuS-X-LC-P and CuPL baseline results using the features uploaded here: https://drive.google.com/drive/u/0/folders/1nzRf13Ha1gvKP_n_4a_JreplA0QkHGBh

Once you verified that you are able to reproduce those results for CUB, I would try to check different number of support set samples. In our experiments, we observed that sometimes StableDiffusion can generate images that highly deviate from the target data distribution, and we would then subsample appropriately. See fig. 6b in the paper for an example of this. 

So the two most important things I would recommend for reproducing the results are:
(1) try to reproduce the SuS-X-LC results and verify you can.
(2) check the result with the CuPL baseline on CUB.
(3) from the set of 15 support set samples per class you generated, try to subsample the first 2 / 4 / 6 per class and check the results with these subsampled support sets (this would mean resulting support set sizes of 400 / 800 / 1200)

I unfortunately wouldn't have time to release the datasets we generated for our reported results until the end of the month due to other conference deadlines, but will be happy to release them sometime in October. Hope this helps, and happy to provide suggestions if you face more issues.

**Comment by Adasunnylily** [comment] 2023-09-03 12:42
thanks!!! I will try as per your instructions.
Another question is I get the error of  
`FileNotFoundError: [Errno 2] No such file or directory: './features/cub_zeroshot_text_weights_mRN50_ptcombined.pt'`
As far as I noticed, there is no combined text_prompt_type for text embedding, is this the "ensemble" type in the code?
Again, thanks for ur kind help.

**Comment by vishaal27** [comment] 2023-09-03 17:26
You should be able to find the combined text prompts here: https://drive.google.com/drive/u/0/folders/1zcmxB_vi2PpGVRFuRwaqJ7MtzGgEsQZk
The combined text prompts are averaged from both the CuPL and the ensemble text prompts (essentially corresponding to CuPL+e from the paper). See this:
https://github.com/vishaal27/SuS-X/blob/d7d4d37881408884999fe276faacdd61b511067f/run_cupl_baseline.py#L141
Let me know if this helps :)

**Comment by Adasunnylily** [comment] 2023-09-04 02:36
It worked!!! I have achieved the reported results for SuS-X-SD-C after changing the 'combined' text_prompt_type, and the results for SuS-X-SD-P and SuS-LC-P are both 48.72 while the reported results are 48.9 and 48.81, slightly lower but improved largely compared to the ensemble text_prompt_type.
Many thanks :)

**Comment by vishaal27** [comment] 2023-09-04 06:26
Awesome, glad you were able to reproduce the results! Closing this for now, feel free to reopen if there are any other issues :)

**Closed as completed by vishaal27** 2023-09-04 06:26 UTC
